import React, { useState } from 'react';
import { X, Copy, Check, FileDown, Shield, Server } from 'lucide-react';
import { EgressInfo, LatencyStats, RouteNode, ServiceUnlockStatus } from '../types';

interface DiagnosticReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  egress: EgressInfo | null;
  stats: LatencyStats;
  downloadSpeed: number;
  uploadSpeed: number;
  peakDownload: number;
  peakUpload: number;
  routes: RouteNode[];
  services: ServiceUnlockStatus[];
}

export const DiagnosticReportModal: React.FC<DiagnosticReportModalProps> = ({
  isOpen,
  onClose,
  egress,
  stats,
  downloadSpeed,
  uploadSpeed,
  peakDownload,
  peakUpload,
  routes,
  services,
}) => {
  const [copied, setCopied] = useState(false);
  const [activeFormat, setActiveFormat] = useState<'markdown' | 'json'>('markdown');

  if (!isOpen) return null;

  const timestamp = new Date().toISOString().replace('T', ' ').substring(0, 19);

  // Markdown format
  const generateMarkdown = () => {
    return `### 🌐 NodePulse 代理网络测速与出口链路诊断报告
- **测试时间**: ${timestamp}
- **出口 IP**: ${egress?.ip || '未知'} (${egress?.ipVersion || 'IPv4'})
- **运营商 / ASN**: ${egress?.asn || '--'} · ${egress?.org || '--'}
- **物理地理位置**: ${egress?.country || '--'} ${egress?.city || ''} (${egress?.countryCode || '--'})
- **Cloudflare Anycast 边缘点**: ${egress?.colo || '--'} (${egress?.coloCity || '--'})
- **IP 属性**: ${egress?.isDatacenter ? '机房云服务器 (Datacenter)' : '原生住宅宽带 (Residential)'}

---
#### ⚡ 速度与稳定性指标 (RFC 3550 规范)
- **下载速率**: 实时 ${downloadSpeed.toFixed(1)} Mbps (峰值: ${peakDownload.toFixed(1)} Mbps)
- **上传速率**: 实时 ${uploadSpeed.toFixed(1)} Mbps (峰值: ${peakUpload.toFixed(1)} Mbps)
- **往返时延 (Ping)**: 中位数 ${stats.median} ms (最快 ${stats.min} ms / 最高 ${stats.max} ms)
- **网络抖动 (Jitter)**: ${stats.jitter} ms
- **数据包丢包率 (Packet Loss)**: ${stats.lossRate.toFixed(1)}% (${stats.lost}/${stats.sent} 丢失)
- **缓冲区膨胀 (Bufferbloat)**: 空闲 ${stats.idlePing}ms / 满载 ${stats.loadedDownloadPing || '--'}ms (评级: ${stats.bufferbloatGrade})

---
#### 🗺️ 跨国中继节点矩阵
${routes
  .map(
    (r) =>
      `- ${r.flag} **${r.name}**: ${
        r.latency !== null ? `${r.latency}ms (抖动: ${r.jitter}ms, 丢包: ${r.lossRate}%)` : '未测试/超时'
      }`
  )
  .join('\n')}

---
#### 🎬 流媒体与常用服务可用性
${services.map((s) => `- **${s.name}**: ${s.status === 'unlocked' ? '✅ 已解锁' : s.status === 'restricted' ? '⚠️ 受限' : '❌ 阻断'} (${s.note})`).join('\n')}

*Generated by NodePulse Network Speed & Diagnostics Tool*
`;
  };

  const generateJson = () => {
    return JSON.stringify(
      {
        timestamp,
        egress,
        metrics: {
          downloadMbps: downloadSpeed,
          peakDownloadMbps: peakDownload,
          uploadMbps: uploadSpeed,
          peakUploadMbps: peakUpload,
          latency: stats,
        },
        routes: routes.map((r) => ({
          name: r.name,
          latency: r.latency,
          jitter: r.jitter,
          lossRate: r.lossRate,
          status: r.status,
        })),
        services: services.map((s) => ({
          name: s.name,
          status: s.status,
          region: s.region,
          note: s.note,
        })),
      },
      null,
      2
    );
  };

  const currentContent = activeFormat === 'markdown' ? generateMarkdown() : generateJson();

  const handleCopy = () => {
    navigator.clipboard.writeText(currentContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm animate-in fade-in duration-150">
      <div className="bg-neutral-950 border border-neutral-800 rounded-2xl w-full max-w-3xl max-h-[85vh] flex flex-col shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="px-6 py-4 border-b border-neutral-800 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Server className="h-4 w-4 text-cyan-400" />
            <span className="font-bold text-sm text-white">网络诊断报告导出</span>
          </div>

          <div className="flex items-center gap-3">
            <div className="flex items-center gap-1 bg-neutral-900 border border-neutral-800 rounded-lg p-0.5 text-xs">
              <button
                onClick={() => setActiveFormat('markdown')}
                className={`px-2.5 py-1 rounded-md transition-colors ${
                  activeFormat === 'markdown' ? 'bg-neutral-800 text-cyan-300 font-medium' : 'text-neutral-400'
                }`}
              >
                Markdown
              </button>
              <button
                onClick={() => setActiveFormat('json')}
                className={`px-2.5 py-1 rounded-md transition-colors ${
                  activeFormat === 'json' ? 'bg-neutral-800 text-cyan-300 font-medium' : 'text-neutral-400'
                }`}
              >
                JSON
              </button>
            </div>

            <button
              onClick={onClose}
              className="p-1 rounded-md text-neutral-400 hover:text-white hover:bg-neutral-800 transition-colors"
            >
              <X className="h-4 w-4" />
            </button>
          </div>
        </div>

        {/* Content Box */}
        <div className="p-6 overflow-y-auto flex-1 font-mono text-xs bg-neutral-900/40 text-neutral-300 select-text leading-relaxed whitespace-pre-wrap">
          {currentContent}
        </div>

        {/* Footer Actions */}
        <div className="px-6 py-4 border-t border-neutral-800 bg-neutral-950 flex items-center justify-between text-xs">
          <span className="text-neutral-500">
            可直接复制并发送至代理节点工单、技术社区或诊断群组
          </span>

          <button
            onClick={handleCopy}
            className="inline-flex items-center gap-1.5 px-4 py-2 text-xs font-semibold text-neutral-950 bg-cyan-400 hover:bg-cyan-300 rounded-lg transition-colors whitespace-nowrap active:scale-[0.98]"
          >
            {copied ? (
              <>
                <Check className="h-3.5 w-3.5 text-neutral-950" />
                <span>已复制到剪贴板</span>
              </>
            ) : (
              <>
                <Copy className="h-3.5 w-3.5" />
                <span>一键复制报告</span>
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};
